apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: idp-project
  namespace: argocd
spec:
  description: AI-Enhanced IDP — managed services
  sourceRepos:
    - "https://github.com/k-shevtsov/ai-enhanced-idp"
  destinations:
    - namespace: argocd
      server: https://kubernetes.default.svc
    - namespace: dev
      server: https://kubernetes.default.svc
    - namespace: staging
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace

