{{- if .Values.monitoring.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Values.service.namespace }}
  labels:
    app: {{ .Values.service.name }}
    release: prometheus
spec:
  selector:
    matchLabels:
      app: {{ .Values.service.name }}
  endpoints:
    - port: http
      path: {{ .Values.monitoring.path }}
      interval: 30s
{{- end }}
